Repository kubevirt/node-maintenance-operator, pull requests merged in 2019-08, with the labels that each got.

#26 Add status fields and updates to maintenance CR
  README.md
  deploy/crds/nodemaintenance_crd.yaml
  pkg/apis/kubevirt/v1alpha1/nodemaintenance_types.go
  pkg/apis/kubevirt/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kubevirt/v1alpha1/zz_generated.openapi.go
  pkg/controller/nodemaintenance/drain.go
  pkg/controller/nodemaintenance/nodemaintenance_controller.go
  pkg/controller/nodemaintenance/nodemaintenance_controller_test.go
  test/e2e/nodemaintenance_test.go
Labels: size/L

#30 Add pod statistics to status
  README.md
  deploy/crds/nodemaintenance_crd.yaml
  pkg/apis/kubevirt/v1alpha1/nodemaintenance_types.go
  pkg/apis/kubevirt/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/nodemaintenance/nodemaintenance_controller.go
  pkg/controller/nodemaintenance/nodemaintenance_controller_test.go
  pkg/controller/nodemaintenance/utils.go
  test/e2e/nodemaintenance_test.go
Labels: size/L

#31 Fix CI dependecies and flow
  Makefile
  automation/check-patch.k8s-1.11.0.packages
  automation/check-patch.k8s-1.13.3.packages
  automation/check-patch.os-3.11.0.packages
  automation/check-patch.packages
  build/make-manifests.sh
  cluster/sync.sh
  hack/release-manifests.sh
Labels: size/M

#29 Add csv-generator script to operator container image
  Makefile
  build/Dockerfile
  build/Dockerfile.registry
  build/csv-generator.sh
  build/make-csv-generator.sh
  build/make-manifests.sh
  manifests/generated/node-maintenance-operator.vVERSION.clusterserviceversion.yaml
Labels: size/L

#32 Adjust retry log message
  pkg/controller/nodemaintenance/drain.go
Labels: size/XS

#35 Fix registry Dockerfile to work with origin-registry-operator 4.2.0
  build/Dockerfile.registry
  manifests/node-maintenance-operator/node-maintenance-operator.package.yaml
  manifests/node-maintenance-operator/v0.4.0/node-maintenance-operator.v0.4.0.clusterserviceversion.yaml
  manifests/node-maintenance-operator/v0.4.0/nodemaintenance_crd.yaml
Labels: size/L

#34 Fix unwanted taint removals
  pkg/controller/nodemaintenance/nodemaintenance_controller_test.go
  pkg/controller/nodemaintenance/taint.go
Labels: size/L

#36 Refactor Logging in controller logic
  Gopkg.lock
  pkg/controller/nodemaintenance/drain.go
  pkg/controller/nodemaintenance/nodemaintenance_controller.go
  pkg/controller/nodemaintenance/taint.go
Labels: size/M

#37 Remove finalizer when node does not exist
  pkg/controller/nodemaintenance/nodemaintenance_controller.go
Labels: size/XS
