Repository kubevirt/node-maintenance-operator, pull requests merged in 2019-04, with the labels that each got.

#1 Operator functionality, deployment and tests
  Gopkg.lock
  README.md
  build/Dockerfile
  build/bin/entrypoint
  build/bin/user_setup
  cmd/manager/main.go
  deploy/crds/kubevirt_v1alpha1_nodemaintenance_cr.yaml
  deploy/crds/kubevirt_v1alpha1_nodemaintenance_crd.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  pkg/apis/addtoscheme_kubevirt_v1alpha1.go
  pkg/apis/apis.go
  pkg/apis/kubevirt/v1alpha1/doc.go
  pkg/apis/kubevirt/v1alpha1/nodemaintenance_types.go
  pkg/apis/kubevirt/v1alpha1/register.go
  pkg/apis/kubevirt/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/kubevirt/v1alpha1/zz_generated.defaults.go
  pkg/apis/kubevirt/v1alpha1/zz_generated.openapi.go
  pkg/controller/add_nodemaintenance.go
  pkg/controller/controller.go
  pkg/controller/nodemaintenance/drain.go
  pkg/controller/nodemaintenance/nodemaintenance_controller.go
  pkg/controller/nodemaintenance/taint.go
  test/e2e/main_test.go
  test/e2e/nodemaintenance_test.go
Labels: size/XXL

#2 Add node name under Spec
  README.md
  deploy/crds/kubevirt_v1alpha1_nodemaintenance_crd.yaml
  deploy/operator.yaml
  pkg/apis/kubevirt/v1alpha1/nodemaintenance_types.go
  pkg/apis/kubevirt/v1alpha1/zz_generated.openapi.go
  pkg/controller/nodemaintenance/nodemaintenance_controller.go
  pkg/controller/nodemaintenance/taint.go
  pkg/controller/nodemaintenance/utils.go
  test/e2e/nodemaintenance_test.go
Labels: size/L

#5 build container images using travis
  .travis.yml
  Makefile
Labels: size/M

#6 Adjust deploy files with namespace
  Gopkg.lock
  README.md
  deploy/crds/nodemaintenance_cr.yaml
  deploy/crds/nodemaintenance_crd.yaml
  deploy/namespace.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
Labels: size/M

#8 Fix CR example to match latest CRD
  deploy/crds/nodemaintenance_cr.yaml
Labels: size/XS

#9 Deploy operator on master nodes
  build/Dockerfile
  deploy/operator.yaml
Labels: size/S

#7 add initial CSV and helper scripts
  .travis.yml
  Makefile
  README.md
  build/Dockerfile.registry
  build/make-olm.sh
  build/update-olm.py
  deploy/olm-catalog/node-maintenance-operator/0.1.0/node-maintenance-operator.v0.1.0.clusterserviceversion.yaml
  deploy/operator.yaml
  manifests/node-maintenance-operator/node-maintenance-operator.package.yaml
  manifests/node-maintenance-operator/v0.1.0/node-maintenance-operator.v0.1.0.clusterserviceversion.yaml
  manifests/node-maintenance-operator/v0.1.0/nodemaintenance_crd.yaml
  olm-deploy-manifests/nm-catalog-source.yaml
  olm-deploy-manifests/nm-ns.yaml
  olm-deploy-manifests/nm-op-group.yaml
  olm-deploy-manifests/nm-sub.yaml
Labels: size/XL

#10 Change CRD to cluster scope
  README.md
  deploy/crds/nodemaintenance_crd.yaml
  test/e2e/nodemaintenance_test.go
Labels: size/S

#11 increased version
  Makefile
  deploy/olm-catalog/node-maintenance-operator/0.2.0/node-maintenance-operator.v0.2.0.clusterserviceversion.yaml
  manifests/node-maintenance-operator/node-maintenance-operator.package.yaml
  manifests/node-maintenance-operator/v0.2.0/node-maintenance-operator.v0.2.0.clusterserviceversion.yaml
  manifests/node-maintenance-operator/v0.2.0/nodemaintenance_crd.yaml
  olm-deploy-manifests/nm-catalog-source.yaml
  olm-deploy-manifests/nm-sub.yaml
Labels: size/L
