Repository kubevirt/node-maintenance-operator, pull requests merged in 2020-07, with the labels that each got.

#92 set owner ref on nmo CR to the node object
  pkg/controller/nodemaintenance/nodemaintenance_controller.go
  pkg/controller/nodemaintenance/nodemaintenance_controller_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#100 Fix requeue on drain error
  Makefile
  go.mod
  hack/functest.sh
  hack/sync.sh
  pkg/controller/nodemaintenance/check_lease_supported_test.go
  pkg/controller/nodemaintenance/check_lease_update_test.go
  pkg/controller/nodemaintenance/lease.go
  pkg/controller/nodemaintenance/nodemaintenance_controller.go
  test/e2e/main_test.go
  test/e2e/nodemaintenance_test.go
Labels: dco-signoff: yes, release-note, size/XL

#101 Fixed make check
  Makefile
  go.mod
  go.sum
  hack/clean.sh
  hack/commit-msg-hook.sh
  hack/coverage.sh
  hack/functest.sh
  hack/gen-crds.sh
  hack/gen-k8s.sh
  hack/gen-operator-sdk.sh
  hack/gen-opm.sh
  hack/generate-bundle.sh
  hack/generate-crds.sh
  hack/generate-index.sh
  hack/generate-k8s.sh
  hack/get-operator-sdk.sh
  hack/get-opm.sh
  hack/precommit-hook.sh
  hack/release-manifests.sh
  hack/sync.sh
  hack/verify-codegen.sh
  hack/verify-manifests.sh
  hack/verify-unchanged.sh
  hack/whitespace.sh
  pkg/apis/nodemaintenance/v1beta1/zz_generated.deepcopy.go
  pkg/controller/nodemaintenance/check_lease_supported_test.go
  pkg/controller/nodemaintenance/check_lease_update_test.go
  pkg/controller/nodemaintenance/lease.go
  pkg/controller/nodemaintenance/nodemaintenance_controller.go
  pkg/controller/nodemaintenance/nodemaintenance_controller_common_test.go
  pkg/controller/nodemaintenance/nodemaintenance_controller_init.go
  pkg/controller/nodemaintenance/nodemaintenance_controller_test.go
  pkg/controller/nodemaintenance/taint.go
Labels: approved, dco-signoff: yes, release-note-none, size/XXL

#103 Removed unused manifests
  olm-deploy-manifests/nm-catalog-source.yaml
  olm-deploy-manifests/nm-ns.yaml
  olm-deploy-manifests/nm-op-group.yaml
  olm-deploy-manifests/nm-sub.yaml
Labels: dco-signoff: yes, release-note-none, size/M

#104 Made some Makefile vars overwritable, use var for CSV metadata's containerImage
  Makefile
  deploy/olm-catalog/node-maintenance-operator/manifests/node-maintenance-operator.clusterserviceversion.yaml
  manifests/node-maintenance-operator/template/node-maintenance-operator.clusterserviceversion.yaml
  manifests/node-maintenance-operator/v0.7.0/manifests/node-maintenance-operator.clusterserviceversion.yaml
Labels: dco-signoff: yes, release-note-none, size/S

#102 Added validation webhook
  Makefile
  cmd/manager/main.go
  deploy/olm-catalog/node-maintenance-operator/manifests/node-maintenance-operator.clusterserviceversion.yaml
  deploy/operatorgroup.yaml
  deploy/webhooks/nodemaintenance.webhook.yaml
  hack/sync.sh
  manifests/node-maintenance-operator/template/node-maintenance-operator.clusterserviceversion.yaml
  manifests/node-maintenance-operator/v0.7.0/manifests/node-maintenance-operator.clusterserviceversion.yaml
  pkg/apis/nodemaintenance/v1beta1/nodemaintenance_api_suite_test.go
  pkg/apis/nodemaintenance/v1beta1/nodemaintenance_validator.go
  pkg/apis/nodemaintenance/v1beta1/nodemaintenance_validator_test.go
  test/e2e/nodemaintenance_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#105 Provide deployment manifests for the latest published images
  Makefile
  README.md
  deploy/deployment-k8s/catalogsource.yaml
  deploy/deployment-k8s/namespace.yaml
  deploy/deployment-k8s/operatorgroup.yaml
  deploy/deployment-k8s/subscription.yaml
  deploy/deployment-ocp/catalogsource.yaml
  deploy/deployment-ocp/namespace.yaml
  deploy/deployment-ocp/operatorgroup.yaml
  deploy/deployment-ocp/subscription.yaml
  hack/generate-bundle.sh
  hack/sync.sh
Labels: dco-signoff: yes, release-note-none, size/L

#106 Improved deployment instructions in README.md
  README.md
Labels: dco-signoff: yes, release-note-none, size/S

#107 Added master quorum validation
  Makefile
  deploy/olm-catalog/node-maintenance-operator/manifests/node-maintenance-operator.clusterserviceversion.yaml
  deploy/role.yaml
  deploy/webhooks/nodemaintenance.webhook.yaml
  hack/functest.sh
  hack/get-opm.sh
  manifests/node-maintenance-operator/v0.7.0/manifests/node-maintenance-operator.clusterserviceversion.yaml
  pkg/apis/nodemaintenance/v1beta1/nodemaintenance_validator.go
  pkg/apis/nodemaintenance/v1beta1/nodemaintenance_validator_test.go
  test/e2e/nodemaintenance_test.go
  test/manifests/fake-etcd-quorum-guard.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#108 Small fixes for manifests
  deploy/olm-catalog/node-maintenance-operator/manifests/node-maintenance-operator.clusterserviceversion.yaml
  deploy/olm-catalog/node-maintenance-operator/node-maintenance-operator.package.yaml
  manifests/node-maintenance-operator/template/node-maintenance-operator.clusterserviceversion.yaml
  manifests/node-maintenance-operator/template/node-maintenance-operator.package.yaml
  manifests/node-maintenance-operator/v0.7.0/manifests/node-maintenance-operator.clusterserviceversion.yaml
  manifests/node-maintenance-operator/v0.7.0/node-maintenance-operator.package.yaml
Labels: dco-signoff: yes, release-note-none, size/S
