Repository kubevirt/node-maintenance-operator, pull requests merged in 2020-04, with the labels that each got.

#69 Improve diagnostics of e2e tests.
  test/e2e/nodemaintenance_test.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/M

#73 move node maintenance operator to its own api group
  README.md
  deploy/crds/nodemaintenance_cr.yaml
  deploy/crds/nodemaintenance_crd.yaml
  deploy/role.yaml
  manifests/generated/node-maintenance-operator.vVERSION.clusterserviceversion.yaml
  pkg/apis/kubevirt/v1alpha1/register.go
  test/e2e/nodemaintenance_test.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, lgtm, size/M

#71 Add bugzilla information to OWNERS
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#60 use upstream drain library instead of local modification.
  Gopkg.toml
  pkg/controller/nodemaintenance/drain.go
  pkg/controller/nodemaintenance/nodemaintenance_controller.go
  vendor/k8s.io/kubectl/pkg/drain/cordon.go
  vendor/k8s.io/kubectl/pkg/drain/default.go
  vendor/k8s.io/kubectl/pkg/drain/drain.go
  vendor/k8s.io/kubectl/pkg/drain/filters.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/XXL
