Repository kubevirt/node-maintenance-operator, pull requests merged in 2020-06, with the labels that each got.

#88 Added slintes to OWNERS
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#87 Fix "external" CI provider
  Makefile
  hack/functest.sh
  hack/sync.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#86 remove multiple empty lines in whitespace fix.
  README.md
  build/csv-generator.sh
  build/make-csv-generator.sh
  build/update-olm.py
  hack/clean.sh
  hack/coverage.sh
  hack/functest.sh
  hack/gen-k8s.sh
  hack/gen-operator-sdk.sh
  hack/release-manifests.sh
  hack/sync.sh
  hack/whitespace.sh
  pkg/controller/nodemaintenance/check_lease_supported_test.go
  pkg/controller/nodemaintenance/lease.go
  pkg/controller/nodemaintenance/nodemaintenance_controller.go
  pkg/controller/nodemaintenance/nodemaintenance_controller_common_test.go
  pkg/controller/nodemaintenance/nodemaintenance_controller_init.go
  pkg/controller/nodemaintenance/nodemaintenance_controller_test.go
  test/e2e/nodemaintenance_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#90 automation test: use the same go version as specified in .travis.yml
  automation/test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#91 whitespace fixes as precommit hook
  Makefile
  hack/commit-msg-hook.sh
  hack/precommit-hook.sh
  hack/whitespace.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#94 fix makefile: phony clause got broken
  Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS
