Repository kubevirt/node-maintenance-operator, pull requests merged in 2020-05, with the labels that each got.

#74 Add coverage report to build
  Makefile
  hack/coverage.sh
  pkg/controller/nodemaintenance/nodemaintenance_controller.go
  pkg/controller/nodemaintenance/nodemaintenance_controller_init.go
Labels: dco-signoff: yes, lgtm, release-note-none, size/L

#70 fix openapi validation error for CRD of node maintenance operator
  deploy/crds/nodemaintenance_crd.yaml
  hack/functest.sh
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/M

#63 Update catalog namespace for OCP 4.2 and higher
  README.md
  olm-deploy-manifests/nm-catalog-source.yaml
  olm-deploy-manifests/nm-sub.yaml
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XS

#79 make cluster-clean broken after using new ci
  Makefile
  hack/clean.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#80 improve log format of nmo
  pkg/controller/nodemaintenance/nodemaintenance_controller.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#82 fix WATCH_NAMESPACE env variable in container spec of generated CSV
  build/csv-generator.sh
  build/make-csv-generator.sh
  deploy/operator.yaml
  manifests/node-maintenance-operator/v0.6.0/node-maintenance-operator.v0.6.0.clusterserviceversion.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S
