Repository kubevirt/node-maintenance-operator, pull requests merged in 2021-01, with the labels that each got.

#149 Fix e2e test failing on missing "Reconciling with fixed duration" log message
  test/e2e/node_maintenance_test.go
Labels: approved, dco-signoff: yes, release-note-none, size/XS

#146 change go version to 1.15
  build/Dockerfile
  go.mod
  go.sum
  vendor/github.com/operator-framework/operator-sdk/pkg/leader/doc.go
  vendor/github.com/operator-framework/operator-sdk/pkg/leader/leader.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/L

#148 add mshitrit as an approver and reviewer
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS
